version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ./mnt/pgdata:/var/lib/postgresql/data/pgdata
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        image: airflow-local:latest
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ../airflow-dags/dags:/usr/local/airflow/dags
            - ./requirements.txt:/requirements.txt
            # - ./plugins:/usr/local/airflow/plugins
            - /var/run/docker.sock:/var/run/docker.sock
            # Linux
            - /usr/bin/docker:/bin/docker:ro
            # Mac
            # - /usr/local/bin/docker:/bin/docker:ro
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3